#ifndef IPC_PUBSUB_COMMON_H
#define IPC_PUBSUB_COMMON_H

#define MQ_PREFIX "/"
#define QUEUE_PERMISSIONS 0660
#define MAX_MESSAGES 10
#define MAX_MSG_SIZE 256
#define MSG_BUFFER_SIZE MAX_MSG_SIZE + 10

#endif /* IPC_PUBSUB_COMMON_H */